# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('publication_date', models.DateField(auto_now_add=True)),
                ('publication_time', models.TimeField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('edit_time', models.TimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=500)),
                ('contentFile', models.CharField(max_length=50)),
            ],
        ),
    ]
