# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='id',
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='blogPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='app.BlogPage'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
