# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170529_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='blogPage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BlogPage'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
