# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170529_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
