# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170529_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='blogPage',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tag',
            field=models.CharField(default='project', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
