# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170606_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
